### ISSUE TITLE
How-To

### ISSUE THREAD

**Issue by csuno** [diamkil/socials#9]
can you please add some Hints...

- how to add custom website Icons
- how to add "Names" for Links?

**Comment by Journetta** [comment]
yeah like i installed it as a docker on unraid.. but it doesn't even create a default configuration file to edit?

hence why i came here to see if there was a default config to edit here

**Comment by csuno** [comment]
here is the default.json https://github.com/diamkil/socials/tree/main/people

**Comment by diamkil** [comment]
> * how to add custom website Icons
Add them in public/img/(name).png
Make sure image is black as css inverts the color for it to be white
> * how to add "Names" for Links?
Coming once I'm done with v2 (express-ejs rewrite)

**Comment by diamkil** [comment]
Main branch is now v2, your json files will need to be edited though
